# Default values for dclaw-design
replicaCount: 1

frontend:
  image:
    repository: dclaw-design-frontend
    tag: local
    pullPolicy: IfNotPresent
  port: 3000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

backend:
  image:
    repository: dclaw-design-backend
    tag: local
    pullPolicy: IfNotPresent
  port: 8096
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  env:
    - name: PORT
      value: "8096"
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: dclaw-design-db-credentials
          key: DATABASE_URL

database:
  enabled: false

ingress:
  enabled: false

service:
  type: ClusterIP

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
